// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalAgendaAPI;

#nullable disable

namespace generic_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250625184238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PersonalAgendaAPI.Models.PostCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplaySettingsId");

                    b.ToTable("postCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "#585858",
                            DisplaySettingsId = 1,
                            TextColor = "#FFFFFF",
                            Title = "Post"
                        },
                        new
                        {
                            Id = 2,
                            BackgroundColor = "#2D416F",
                            DisplaySettingsId = 2,
                            TextColor = "#FFFFFF",
                            Title = "Work"
                        });
                });

            modelBuilder.Entity("PersonalAgendaAPI.Models.PostCategoryDisplaySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("postCategoryDisplaySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Index = 1
                        },
                        new
                        {
                            Id = 2,
                            Index = 2
                        });
                });

            modelBuilder.Entity("PersonalAgendaAPI.Models.PostCategory", b =>
                {
                    b.HasOne("PersonalAgendaAPI.Models.PostCategoryDisplaySettings", "DisplaySettings")
                        .WithMany()
                        .HasForeignKey("DisplaySettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplaySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
